routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Admin\ImportantLinks;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Website\HomeController;
use App\Http\Controllers\Admin\AllImageController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\HeroSliderController;
use App\Http\Controllers\Admin\PostCategoryController;
// use App\Http\Controllers\Subscribe\Auth\ForgotPasswordController;


// Website Routes

// Cache Clear
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
});



Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/photo-gallery', [HomeController::class, 'photoGallery'])->name('photo-gallery');
Route::get('/video-gallery', [HomeController::class, 'videoGallery'])->name('video-gallery');
Route::get('/all-news', [HomeController::class, 'allNews'])->name('all-news');


Route::get('/fsingle-footer-detais{id}', [HomeController::class, 'singleFooterTextDetails'])->name('single-footer-detais');
Route::get('/contact-us', [HomeController::class, 'contactUs'])->name('contact-us');
Route::post('/contact-us/message', [HomeController::class, 'contactUsMessage'])->name('contact-us.message');










// Route::group(['prefix' => 'membership', 'as'=>'membership.'], function () {
//     Route::get('/login',  [SubscribeLoginController::class, 'showLoginForm'])->name('login');
//     Route::post('/login',  [SubscribeLoginController::class, 'login' ])->name('login.submit');
//     Route::post('/logout', [SubscribeLoginController::class, 'logout' ])->name('logout');

//     Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])
//         ->name('password.request');

//     Route::post('/password/email', [ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');

//     Route::get('/password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');

//     Route::post('/password/reset', [ResetPasswordController::class, 'reset']);

// });


Route::group(['prefix' => '/admin', 'as'=>'admin.'], function () {
	
});


// Admin Panel Routes
Route::group(['middleware' =>'auth'], function () {
	Route::group(['prefix' => '/admin', 'as'=>'admin.'], function () {
		// Admin Module

		Route::resource('/category', PostCategoryController::class);

		Route::match(['get', 'post'],'/settings', [SettingController::class, 'create'])->name('settings');
		// Route::get('/settings', [SettingController::class, 'create'])->name('settings');
		// Route::post('/settings/store', [SettingController::class, 'update'])->name('settings-store');


		Route::get('/profile-edit/{id}', [AdminController::class, 'profileEdit'])->name('profile-edit');
		Route::put('/profile-update/{id}', [AdminController::class, 'profileUpdate'])->name('profile-update');

		// Dashboard Home Module
		Route::get('/', [DashboardController::class, 'dashboard'])->name('dashboard');
	
        Route::resource('/hero-slider', HeroSliderController::class);

 


		// All Image Module
		Route::get('/all-images', [AllImageController::class, 'index'])->name('all-images');
		Route::post('/all-image/store', [AllImageController::class, 'store'])->name('all-image.store');
		Route::delete('/all-image/destroy/{id}', [AllImageController::class, 'destroy'])->name('all-image.destroy');

		
		// Photo & Video Gallery Module
		Route::get('/photo-gallery', [AllImageController::class, 'photoGallery'])->name('photo-gallery');
		Route::post('/photo-gallery/store', [AllImageController::class, 'photoGalleryStore'])->name('photo-gallery.store');
		Route::delete('/photo-gallery/destroy/{id}', [AllImageController::class, 'photoGalleryDestroy'])->name('photo-gallery.destroy');

		Route::get('/video-gallery', [AllImageController::class, 'videoGallery'])->name('video-gallery');
		Route::post('/video-gallery.store', [AllImageController::class, 'videoGalleryStore'])->name('video-gallery.store');
		Route::delete('/video-gallery/destroy/{id}', [AllImageController::class, 'videoGalleryDestroy'])->name('video-gallery.destroy');



        Route::resource('/important-links', ImportantLinks::class);

	});
});

Auth::routes(['register' => false, 'verify' => true]);

app/Models/VideoGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class VideoGallery extends Model
{
    use HasFactory;
    protected $fillable = [
    	'video_url',
    ];
}

resources/views/admin/video-gallery/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon"> <i class="pe-7s-display1 icon-gradient bg-premium-dark"></i>
                    </div>
                    <div>Video Gallery Video List
                    </div>
                    <button type="button" class="btn btn-primary float-right add-new-modal-btn">Add New</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-card mb-3 card">
                    <div class="card-body">
                        {{-- <h5 class="card-title">Simple table</h5> --}}
                        <table id="table_id" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Video</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if($video_gallery_data->count() > 0)
                                    @foreach ($video_gallery_data as $video)
                                    <tr>
                                        <td>{{ $loop->index+1 }}</td>
                                        <td class="all-video-iframe">
                                            {!! $video->video_url !!}
                                        </td>
                                        <td>
                                            <div class="action-btns">
                                               {{--  <a class="data-edit-btn" data-toggle="tooltip" data-placement="top" title="Edit" href="{{ route('admin.post-category.edit', $category->id) }}">
                                                <i class="fas fa-edit"></i>
                                                </a> --}}
                                                <form method="POST" action="{{ route('admin.video-gallery.destroy', $video->id) }}" accept-charset="UTF-8">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="data-delete-btn" data-toggle="tooltip" data-placement="top" title="Delete Category"><i class="fas fa-trash"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                @else
                                <h3 style="text-alig:center"> No Post Found</h3>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add New Category Form Modal -->
    <div class="add-new-modal-wrapper">
        <div class="add-new-modal-inner">
            <div class="main-card card">
                <div class="card-body">
                    <div class="card-top-wrapper">
                        <h5 class="card-title">Upload New Video(s)</h5>
                        <div class="modal-hide-btn"><i class="fas fa-times"></i></div>
                    </div>
                    <form action="{{ route('admin.video-gallery.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="position-relative form-group border-0">
                            <label class="mb-0">Video Embeded Link</label>
                            <div class="avatar-upload top-photo">
                                <div class="product-video-items-wrapper">
                                    <div class="product-cover-photo">
                                        <input class="form-control p-cover-photo" type="text"  name="video_url[]" required>
                                        <div class="p-video-new-item-add-btn"><i class="fas fa-plus"></i>Add New</div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                        <button class="mt-1 btn btn-primary p-store-btn" type="submit">Submit</button>
                        <button class="mt-1 btn modal-hide-btn cancel" type="reset">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop