routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Admin\ImportantLinks;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Website\HomeController;
use App\Http\Controllers\Admin\AllImageController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\HeroSliderController;
use App\Http\Controllers\Admin\PostCategoryController;
// use App\Http\Controllers\Subscribe\Auth\ForgotPasswordController;


// Website Routes

// Cache Clear
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
});



Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/photo-gallery', [HomeController::class, 'photoGallery'])->name('photo-gallery');
Route::get('/video-gallery', [HomeController::class, 'videoGallery'])->name('video-gallery');
Route::get('/all-news', [HomeController::class, 'allNews'])->name('all-news');


Route::get('/fsingle-footer-detais{id}', [HomeController::class, 'singleFooterTextDetails'])->name('single-footer-detais');
Route::get('/contact-us', [HomeController::class, 'contactUs'])->name('contact-us');
Route::post('/contact-us/message', [HomeController::class, 'contactUsMessage'])->name('contact-us.message');










// Route::group(['prefix' => 'membership', 'as'=>'membership.'], function () {
//     Route::get('/login',  [SubscribeLoginController::class, 'showLoginForm'])->name('login');
//     Route::post('/login',  [SubscribeLoginController::class, 'login' ])->name('login.submit');
//     Route::post('/logout', [SubscribeLoginController::class, 'logout' ])->name('logout');

//     Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])
//         ->name('password.request');

//     Route::post('/password/email', [ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');

//     Route::get('/password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');

//     Route::post('/password/reset', [ResetPasswordController::class, 'reset']);

// });


Route::group(['prefix' => '/admin', 'as'=>'admin.'], function () {
	
});


// Admin Panel Routes
Route::group(['middleware' =>'auth'], function () {
	Route::group(['prefix' => '/admin', 'as'=>'admin.'], function () {
		// Admin Module

		Route::resource('/category', PostCategoryController::class);

		Route::match(['get', 'post'],'/settings', [SettingController::class, 'create'])->name('settings');
		// Route::get('/settings', [SettingController::class, 'create'])->name('settings');
		// Route::post('/settings/store', [SettingController::class, 'update'])->name('settings-store');


		Route::get('/profile-edit/{id}', [AdminController::class, 'profileEdit'])->name('profile-edit');
		Route::put('/profile-update/{id}', [AdminController::class, 'profileUpdate'])->name('profile-update');

		// Dashboard Home Module
		Route::get('/', [DashboardController::class, 'dashboard'])->name('dashboard');
	
        Route::resource('/hero-slider', HeroSliderController::class);

 


		// All Image Module
		Route::get('/all-images', [AllImageController::class, 'index'])->name('all-images');
		Route::post('/all-image/store', [AllImageController::class, 'store'])->name('all-image.store');
		Route::delete('/all-image/destroy/{id}', [AllImageController::class, 'destroy'])->name('all-image.destroy');

		
		// Photo & Video Gallery Module
		Route::get('/photo-gallery', [AllImageController::class, 'photoGallery'])->name('photo-gallery');
		Route::post('/photo-gallery/store', [AllImageController::class, 'photoGalleryStore'])->name('photo-gallery.store');
		Route::delete('/photo-gallery/destroy/{id}', [AllImageController::class, 'photoGalleryDestroy'])->name('photo-gallery.destroy');

		Route::get('/video-gallery', [AllImageController::class, 'videoGallery'])->name('video-gallery');
		Route::post('/video-gallery.store', [AllImageController::class, 'videoGalleryStore'])->name('video-gallery.store');
		Route::delete('/video-gallery/destroy/{id}', [AllImageController::class, 'videoGalleryDestroy'])->name('video-gallery.destroy');



        Route::resource('/important-links', ImportantLinks::class);

	});
});

Auth::routes(['register' => false, 'verify' => true]);

resources/views/admin/_partials/footer.blade.php
<div class="app-wrapper-footer">
   <div class="app-footer">
      <div class="app-footer__inner">
         <div class="app-footer-left">
            <ul class="nav">
               <li class="nav-item text-center w-100">
                  <a href="javascript:void(0);" class="nav-link d-block">
                    Copyright © Habigonj Zila Samiti {{date("Y")}}. Website Developed & Maintenance by BijoyTech
                  </a>
               </li>
               {{-- <li class="nav-item">
                  <a href="javascript:void(0);" class="nav-link">
                  Footer Link 2
                  </a>
               </li> --}}
            </ul>
         </div>
         {{-- <div class="app-footer-right">
            <ul class="nav">
               <li class="nav-item">
                  <a href="javascript:void(0);" class="nav-link">
                  Footer Link 3
                  </a>
               </li>
               <li class="nav-item">
                  <a href="javascript:void(0);" class="nav-link">
                     <div class="badge badge-success mr-1 ml-0">
                        <small>NEW</small>
                     </div>
                     Footer Link 4
                  </a>
               </li>
            </ul>
         </div> --}}
      </div>
   </div>
</div>

resources/views/admin/_partials/page-header.blade.php
<div class="app-page-title">
   <div class="page-title-wrapper">
      <div class="page-title-heading">
         <div class="page-title-icon">
            <i class="pe-7s-car icon-gradient bg-mean-fruit">
            </i>
         </div>
         <div>
            Analytics Dashboard
            <div class="page-title-subheading">This is an example dashboard created using build-in elements and components.
            </div>
         </div>
      </div>
      <div class="page-title-actions">
         <button type="button" data-toggle="tooltip" title="Example Tooltip" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark">
         <i class="fa fa-star"></i>
         </button>
         <div class="d-inline-block dropdown">
            <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn-shadow dropdown-toggle btn btn-info">
            <span class="btn-icon-wrapper pr-2 opacity-7">
            <i class="fa fa-business-time fa-w-20"></i>
            </span>
            Buttons
            </button>
            <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
               <ul class="nav flex-column">
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                        <i class="nav-link-icon lnr-inbox"></i>
                        <span>
                        Inbox
                        </span>
                        <div class="ml-auto badge badge-pill badge-secondary">86</div>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                        <i class="nav-link-icon lnr-book"></i>
                        <span>
                        Book
                        </span>
                        <div class="ml-auto badge badge-pill badge-danger">5</div>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                     <i class="nav-link-icon lnr-picture"></i>
                     <span>
                     Picture
                     </span>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a disabled href="javascript:void(0);" class="nav-link disabled">
                     <i class="nav-link-icon lnr-file-empty"></i>
                     <span>
                     File Disabled
                     </span>
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</div>

resources/views/admin/_partials/page-title.blade.php
<div class="app-page-title">
   <div class="page-title-wrapper">
      <div class="page-title-heading">
         <div class="page-title-icon">
            <i class="pe-7s-car icon-gradient bg-mean-fruit">
            </i>
         </div>
         <div>
           Admin Dashboard
            <div class="page-title-subheading">
            </div>
         </div>
      </div>
      <div class="page-title-actions">
         <button type="button" data-toggle="" title="Example Tooltip" data-placement="bottom" class="btn-shadow mr-3 btn btn-dark" style="cursor:auto">
         <i class="fa fa-star"></i>
         </button>
         <div class="d-inline-block dropdown">
            <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn-shadow dropdown-toggle btn btn-info" style="cursor:auto">
            <span class="btn-icon-wrapper pr-2 opacity-7">
            <i class="fa fa-business-time fa-w-20"></i>
            </span>
            Juktarastra Habigonj Zila Samiti Inc
            </button>
            {{-- <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
               <ul class="nav flex-column">
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                        <i class="nav-link-icon lnr-inbox"></i>
                        <span>
                        Inbox
                        </span>
                        <div class="ml-auto badge badge-pill badge-secondary">86</div>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                        <i class="nav-link-icon lnr-book"></i>
                        <span>
                        Book
                        </span>
                        <div class="ml-auto badge badge-pill badge-danger">5</div>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a href="javascript:void(0);" class="nav-link">
                     <i class="nav-link-icon lnr-picture"></i>
                     <span>
                     Picture
                     </span>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a disabled href="javascript:void(0);" class="nav-link disabled">
                     <i class="nav-link-icon lnr-file-empty"></i>
                     <span>
                     File Disabled
                     </span>
                     </a>
                  </li>
               </ul>
            </div> --}}
         </div>
      </div>
   </div>
</div>

resources/views/admin/_partials/pass-recovery.blade.php
<link href="{{asset('/')}}admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="{{asset('/')}}admin/assets/css/style.css" rel="stylesheet" type="text/css">
<link href="{{ asset('/') }}admin/assets/css/custom.style.css" rel="stylesheet" />

resources/views/admin/_partials/scripts.blade.php
{{-- <script src="http://maps.google.com/maps/api/js?sensor=true"></script> --}}

<script type="text/javascript" src="{{ asset('assets/admin/scripts/main.js/') }}"></script>


<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js "></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{{ asset('assets/toastr/js/toastr.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/admin/scripts/custom.js/') }}"></script>
<script type="text/javascript">
    // toastr script
    @if (Session::has('message'))
        toastr.success('{{Session::get('message')}}');
    @elseif(Session::has('error'))
        toastr.error('{{Session::get('error')}}');

    @elseif($errors)
        @foreach ($errors->all() as $error)
            toastr.error('{{$error}}');
        @endforeach
    @endif
</script>


<script>

    // $(document).ready(function () {
    //     $('table tbody').sortable({
    //         update: function (event, ui) {
    //             $(this).find('tr').each(function (index) {
    //                 if ($(this).attr('data-position') != (index+1)) {
    //                     $(this).attr('data-position', (index+1)).addClass('updated');
    //                 }
    //             });
    //             saveNewPositions();
    //         }
    //     });
    // });

    // function saveNewPositions() {
    //     var positions = [];
    //     $('.updated').each(function () {
    //         positions.push([$(this).attr('data-index'), $(this).attr('data-position')]);
    //         $(this).removeClass('updated');
    //     });

    //     $.ajax({
    //         url: '',
    //         method: 'GET',
    //         dataType: 'text',
    //         data: {
    //             update: 1,
    //             positions: positions
    //         }, 
    //         success: function (response) {
    //             console.log(response);
    //         }
    //     });
    // }

</script>

resources/views/admin/_partials/sidebar.blade.php
<div class="app-sidebar sidebar-shadow">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar"> <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">

                @php

                    // $heroSliderEdit  = strpos($_SERVER['REQUEST_URI'], '/admin/hero-slider/');
                @endphp

                <li>
                    <a href="{{route('admin.dashboard')}}" class="{{ request()->is('admin') ? 'mm-active' : '' }}">
                        <i class="metismenu-icon fas fa-tachometer-alt"></i>
                        Dashboard
                    </a>
                </li>

                <li class="sm-link">
                    <a href="#" class="">

                        <i class="metismenu-icon fas fa-clipboard-list"></i>
                        Categories
                        <i class="metismenu-state-icon fas fa-chevron-down"></i>
                    </a>
                    <ul>
                        <li>
                            <a href="{{ route('admin.category.create') }}" class="{{ request()->is('admin/category/create') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon"></i>
                                Add Category
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('admin.category.index') }}" class="{{ request()->is('admin/category') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon fas fa-clipboard-list"></i>
                                All Category
                            </a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{{ route('admin.category.index') }}" class="{{ request()->is('admin/category') ? 'mm-active' : '' }}">
                        <i class="metismenu-icon fas fa-clipboard-list"></i>
                        All Category
                    </a>
                </li>
                    
            
                <li class="sm-link">
                    <a href="#" class="">

                        <i class="metismenu-icon fas fa-clipboard-list"></i>
                        Posts
                        <i class="metismenu-state-icon fas fa-chevron-down"></i>
                    </a>
                    <ul>
                        <li>
                            <a href="" class="{{ request()->is('admin/posts') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon"></i>
                                All Posts
                            </a>
                        </li>
                        <li>
                            <a href=""  class="{{ request()->is('admin/post/create') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon pe-7s-mouse"></i>
                            Add New Post</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{{ route('admin.all-images') }}" class="{{ request()->is('admin/all-images') ? 'mm-active' : '' }}">
                        <i class="metismenu-icon fas fa-clipboard-list"></i>
                        All Image List
                    </a>
                </li>
                

                <li class="sm-link">
                    <a href="#">
                        <i class="metismenu-icon fas fa-clipboard-list"></i>
                        Photo & Video Gallery
                        <i class="metismenu-state-icon fas fa-chevron-down"></i>
                    </a>
                    <ul>
                        <li>
                            <a href="{{route('admin.photo-gallery')}}" class="{{ request()->is('admin/photo-gallery') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon"></i>
                                Photo Gallery
                            </a>
                        </li>
                        <li>
                            <a href="{{route('admin.video-gallery')}}" class="{{ request()->is('admin/video-gallery') ? 'mm-active' : '' }}">
                                <i class="metismenu-icon"></i>
                                Video Gallery
                            </a>
                        </li>
                    </ul>
                </li>
   
                <li>
                    <a href="" class="{{ request()->is('admin/home-intro') ? 'mm-active' : '' }}">
                         <i class="metismenu-icon fas fa-clipboard-list"></i>
                        Settings
                    </a>
                </li>                    
            
            </ul>
        </div>
    </div>
</div>

resources/views/admin/_partials/stylesheets.blade.php
<meta charset="utf-8" />
<title>{{ str_replace('_', ' ', config('app.name')) }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="Admin Dashboard" name="description" />
<meta content="ThemeDesign" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<link rel="shortcut icon" href="{{ asset('assets/favicon-icon.png') }}">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />


<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">


<link href="{{asset('assets/toastr/css/toastr.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/css/main.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/css/font-face.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/css/custom.css')}}" rel="stylesheet">
<script src="{{asset('assets/sweet-alert.min.js')}}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

resources/views/admin/_partials/top-header.blade.php
<div class="app-header header-shadow">
   <div class="app-header__logo">
      <div class="logo-src"><h2>Admin Panel</h2></div>
      <div class="header__pane ml-auto">
         <div>
            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
            <span class="hamburger-box">
            <span class="hamburger-inner"></span>
            </span>
            </button>
         </div>
      </div>
   </div>
   <div class="app-header__mobile-menu">
      <div>
         <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
         <span class="hamburger-box">
         <span class="hamburger-inner"></span>
         </span>
         </button>
      </div>
   </div>
   <div class="app-header__menu">
      <span>
      <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
      <span class="btn-icon-wrapper">
      <i class="fa fa-ellipsis-v fa-w-6"></i>
      </span>
      </button>
      </span>
   </div>
   <div class="app-header__content">
      <div class="app-header-right">
         <div class="header-btn-lg pr-0">
            <div class="widget-content p-0">
               <div class="widget-content-wrapper">
                  <div class="widget-content-left">
                     <div class="btn-group">
                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                        @if(Auth::user()->image)
                        <img width="42" class="rounded-circle" src="{{ asset(Auth::user()->image) }}" alt="">
                        @else
                        <img width="42" class="rounded-circle" src="{{ asset('assets/admin/images/avatars/images.jpg') }}" alt="">
                        @endif
                        <i class="fa fa-angle-down ml-2 opacity-8"></i>
                        </a>
                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{{route('admin.profile-edit', Auth::user()->id)}}">User Profile</a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                document.getElementById('form_logout').submit();
                                "> Logout </a>


                            <form id="form_logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>

                        </div>
                     </div>
                  </div>
                  <div class="widget-content-left  ml-3 header-user-info">
                     <div class="widget-heading">
                        {{ Auth::user()->name }}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>